name: 'oc new-app'
description: 'Deploy and Expose an app on Openshift'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  image:
    description: 'The name (reference) of the image to create deployment'
    required: true
  port:
    description: 'The tags of the image to build. For multiple tags, seperate by a space. For example, "latest v1".'
    required: false
    default: latest
  app_name:
    description: 'The base image to use to create a new container image'
    required: false
outputs:
  image:
    description: 'Name of the image built'
  tags:
    description: 'List of the tags that were created, separated by spaces'
runs:
  using: 'node12'
  main: 'dist/index.js'
