name: 'oc-new-app'
description: 'Deploy and expose an application on OpenShift'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  app_name:
    description: "Name to use for generated application artifacts"
    required: true
  create_pull_secret_from:
    description: "Auth file from which to create pull secret, accepted values are 'docker' and 'podman'"
    required: false
  image:
    description: "The name (reference) of the image to create deployment"
    required: true
  namespace:
    description: "The OpenShift project/Kubernetes namespace to deploy to. Defaults to current context's."
    required: false
  port:
    description: "The port to use for the application"
    required: false
  registry:
    description: "The Hostname/domain of the container image registry such as quay.io, docker.io. to create pull secret"
    required: false
  registry_username:
    description: "Registry username to create pull secret"
    required: false
  registry_password:
    description: "Password, encrypted password, or access token of the provided registry"
    required: false

outputs:
  route:
    description: "Service route of the deployed application"
  selector:
    description: "Selector to filter out the deployment"
runs:
  using: 'node12'
  main: 'dist/index.js'
